### ISSUE TITLE
Could not find CIFs

### ISSUE THREAD

**Issue by jianhaoc** [kuixu/alphafold#6]
Hi, I can't run alphafold deamon after installation (see below).
$ python3 run_alphafold.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --output_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --model_names has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --data_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --uniref90_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --mgnify_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --uniclust30_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --bfd_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --pdb70_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --template_mmcif_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --max_template_date has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --obsolete_pdbs_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
E0808 08:51:38.610640 140055556486976 templates.py:860] Could not find CIFs in /data01/xukui/alphafold/pdb_mmcif/mmcif_files
Traceback (most recent call last):
  File "run_alphafold.py", line 338, in <module>
    app.run(main)
  File "/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda3/envs/af2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 265, in main
    template_featurizer = templates.TemplateHitFeaturizer(
  File "/data2/sw/af-kuixu/alphafold/alphafold/data/templates.py", line 861, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in /data01/xukui/alphafold/pdb_mmcif/mmcif_files

Did I miss anything to change the default path /data01/xukui/alphafold/pdb_mmcif/mmcif_files to my own path? Thank you!

**Comment by kuixu** [comment]
Please change the `DOWNLOAD_DIR`.

```
# Set to target of scripts/download_all_databases.sh
DOWNLOAD_DIR = '/path/to/database'

# Path to a directory that will store the results.
output_dir = '/path/to/output_dir'

```

**Comment by clemensgrimm** [comment]
Same problem here:
```
$ echo $DOWNLOAD_DIR
/home/clemens/alphafold/parameter/
```
but:
```
$ exp/run_local.sh T1050.fasta
[...]
 ValueError: Could not find CIFs in /data01/xukui/alphafold/pdb_mmcif/mmcif_files
```

**Comment by clemensgrimm** [comment]
Problem might be that running  scripts/download_all_data.sh does not download the PDB data. Reason might be that in scripts/download_pdb_mmcif.sh the relevant commands are commented out (?!):
```
echo "Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)..."
mkdir --parents "${RAW_DIR}"
# rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
#   rsync.rcsb.org::ftp_data/structures/divided/mmCIF/ \
#   "${RAW_DIR}"

# rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
#   data.pdbj.org::ftp_data/structures/divided/mmCIF/ \
#   "${RAW_DIR}"
```

**Comment by chesterroh** [comment]
> Problem might be that running scripts/download_all_data.sh does not download the PDB data. Reason might be that in scripts/download_pdb_mmcif.sh the relevant commands are commented out (?!):
> 
> ```
> echo "Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)..."
> mkdir --parents "${RAW_DIR}"
> # rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
> #   rsync.rcsb.org::ftp_data/structures/divided/mmCIF/ \
> #   "${RAW_DIR}"
> 
> # rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
> #   data.pdbj.org::ftp_data/structures/divided/mmCIF/ \
> #   "${RAW_DIR}"
> ```

I tried to download mmCIF files by uncommenting the former one in the installer file described above. But after having spent several hours of downloading it via rsync, I got to understand why @kuixu commented it out on purpose. It's really really slow. It would take more than a week I guess.

Please try to download it directly from ftp.pdbj.org or other equivalent mirror sites by using 'wget -r' or other recursive download tools. It takes much shorter time.
